import React, {useEffect} from 'react';
import '../documents/style.css';

const Documents = () => {
  useEffect(() => {
    const hash = window.location.hash;
    if (hash) {
      const element = document.querySelector(hash);
      if (element) {
        const elementPosition = element.getBoundingClientRect().top + window.scrollY;
        const offset = 100; 
        window.scrollTo({
          top: elementPosition - offset,
          behavior: 'smooth',
        });
      }
    }
  }, []);
  return (
    <>
    <div className='doc_con1'  id='first' >
        <h1>Privacy Policy</h1>
        <p>Last updated: November 15, 2024</p>
        <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
        <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
        <h1>Interpretation and Definitions</h1>
        <h2>Interpretation</h2>
        <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
        <h1>Definitions</h1>
        <p>For the purposes of this Privacy Policy:</p>
        <li>Account means a unique account created for You to access our Service or parts of our Service.</li>
        <li>Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
        <li>Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Cubicdt LLC, 419 6TH AVE SIDNEY, OH 45365.</li>
        <li>Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
        <h1>Country refers to: Ohio, United States</h1>
        <p>Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p>
        <p>Personal Data is any information that relates to an identified or identifiable individual.</p>
        <h1>Service refers to the Website.</h1>
        <p>Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p>
        <p>Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
        <p>Website refers to Cubicdt LLC, accessible from http://cubicdtllc.com/#operation</p>
        <p>You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
    </div>
    <div className='doc_con1'>
        <h1>Tracking Technologies and Cookies</h1>
        <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
        <p>Cookies or Browser Cookies. A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</p>
        <p>Web Beacons. Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</p>
        <p>Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. You can learn more about cookies on TermsFeed website article.</p>
        <h1>We use both Session and Persistent Cookies for the purposes set out below:</h1>
        <p>Necessary / Essential Cookies</p>
        <p>Type: Session Cookies</p>
        <p>Administered by: Us</p>
        <p>Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</p>
        <p>Functionality Cookies</p>
        <p>Type: Persistent Cookies</p>
        <p>Administered by: Us</p>
        <p>Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</p>
        <p>For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>
        <h1>Use of Your Personal Data</h1>
        <p>The Company may use Personal Data for the following purposes:</p>
        <p>To provide and maintain our Service, including to monitor the usage of our Service.</p>
        <p>To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</p>
        <p>For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</p>
        <p>To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</p>
        <p>To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</p>
        <p>To manage Your requests: To attend and manage Your requests to Us.</p>
        <p>For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</p>
        <p>For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</p>
        <p>We may share Your personal information in the following situations:</p>
        <p>With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.
For business transfers: We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.
With Affiliates: We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.
With business partners: We may share Your information with Our business partners to offer You certain products, services or promotions.
With other users: when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.
With Your consent: We may disclose Your personal information for any other purpose with Your consent.
Retention of Your Personal Data
The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
        <p>The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</p>
    </div>



    <div className='doc_con1'>
    <h1>Transfer of Your Personal Data</h1>
        <p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</p>
        <p>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
        <p>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>
        <h1>Delete Your Personal Data</h1>
        <p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</p>
        <p>Our Service may give You the ability to delete certain information about You from within the Service.</p>
        <p>You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.</p>
        <p>Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.</p>
        <h1>Disclosure of Your Personal Data</h1>
        <h2>Business Transactions</h2>
        <p>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
        <h1>Law enforcement</h1>
        <p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
        <h1>Other legal requirements</h1>
        <p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
        <h1>Children's Privacy</h1>
        <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</p>
        <p>If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.</p>
        <h1>Links to Other Websites</h1>
        <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
        <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
        <h1>Changes to this Privacy Policy</h1>
        <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
        <p>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.</p>
        <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
        <h1>Contact Us</h1>
        <h2>If you have any questions about this Privacy Policy, You can contact us:</h2>
        <p>By email: cubitsafety2022@gmail.com</p>
        <p>By visiting this page on our website: http://cubicdtllc.com/#operation</p>
        <p>By phone number: 380.201.7145</p>
        <p>SMS consent and phone numbers provided for SMS purposes will not be shared with any third parties or affiliates for marketing purposes.</p>
    </div>

    <div className='doc_con1'>
    <h1>SMS For Consent Communication</h1>
        <p>The information (+13802017145) obtained as part of the SMS consent process will not be shared with third parties for marketing purposes.</p>
        <p>Types of SMS Communications</p>
        <p>If you have consented to receive text messages from [CUBICDT LLC], you may receive text messages related to appointment reminders, meetings, and follow up on cases. </p>
        <p>For Example: Hello Thank you for contacting (CUBICDT LLC), how can we help you? Reply Stop to opt-out at any time. Message and data rates may apply, for assistance, text Help" or visit our [http://cubicdtllc.com/documents#first] and [http://cubicdtllc.com/documents#first]</p>
        <p>Please be advised this is just an example as you should adjust or accommodate this based on the type of messages your company would send to your customers. </p>
        <p>Furthermore, it is important to cover the following throughout this SMS Terms And Conditions portion: </p>
        <p>Message Frequency: Provide an estimated amount of SMS messages you would be sending daily across all users. </p>
        <p>For example, Our SMS message frequency will be from 50 to 1000 text messages daily across all users. </p>
        <p>Potential Fees for SMS Messaging: Many carriers charge a fee for each message sent or received. This can vary depending on the carrier's pricing structure and whether the message is sent domestically or internationally. Please give a brief explanation about potential fees for any received or sent text message your customer could get from their losing carrier, so they are aware of any potential fee for SMS messaging interaction with your company, any carrier may vary their fees for SMS messaging based on several factors such as, geographic location, and the type of SMS messaging being used (e.g., promotional, transactional, or one-time passwords)</p>
        <p>Opt-In Method: Customers will Opt-In for SMS messaging from (CUBICDT LLC) through intakes forms on their website located at (http://cubicdtllc.com/), this agreement for SMS will not be shared with third parties for marketing purposes.</p>
        <p>Opt-out: Customers will be able to Opt-out for SMS messaging from (CUBICDT LLC) by replying STOP at any time to any received SMS message, once opted-out they will receive no further SMS communication. They can Opt back In at any time by replying START</p>
        <p>If your SMS Terms And Conditions will be within your privacy policy, please refer to it by adding the actual hyperlink that will take to your privacy policy for Customers to review it in detail, if your SMS Terms And Conditions will be built up in a stand-alone document please do the same, referring to the privacy policy will be highly recommended and will limit delays in the SMS approval process.</p>
    </div>
    </>
  )
}

export default Documents;